### PR TITLE
Add hot reload during development

### LINKED ISSUE #3064: Ability for dev environment to have hot reloading (Reload on file save)
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.4 (17E202)
- **Hyper.app version**: 2.1.0-canary.1 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist here](https://gist.github.com/El-Dringo-Brannde/ce76b3079d6a5f8cfffd02882b52cb06)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

I was curious if anyone would be interested in me changing the `yarn dev` (or something similar) script such that it allows for the dev environment to be reloaded on file changes. 

I know currently we have the webpack doing a re-compile, I mean refreshing the actual window.

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Closes #3064

### CODE REVIEW

**Comment by LabhanshAgrawal** [comment]
Looks like there's an issue during reload when editing files in the app directory
as these files are part of the main process editing these causes `electron-reloader` to restart electron from scratch, thus detaching it from the terminal.

This would be troublesome when someone needs the console output during development.

On making changes to files in lib directory, it just reloads the window and everything seems ok.

If this sounds ok, then we can use it, else we'd need to look for workarounds.

**Comment by LabhanshAgrawal** [comment]
Use https://github.com/catdad/electronmon instead.
This solves the detach issue.

**Comment by Stanzilla** [comment]
meh the github merge resolution uses merge instead of rebase, sorry. Can you rebase and force push please?

**Comment by LabhanshAgrawal** [comment]
sure no problem

**Comment by LabhanshAgrawal** [comment]
pushed

**Pull request merged**
