### PR TITLE
Added travis arm64 builds

### LINKED ISSUE #3337: Build for Linux ARM devices
any plans for a Linux ARM build? if nobody else is on it or has attempted it, i can give it a try.

### PR DESCRIPTION
**Pull request by danacr**
Fixes #3337, #4135 and #4375

Released on my fork: https://github.com/danacr/hyper/releases/tag/3.1.0-canary.4-arm64

### CODE REVIEW

**Comment by danacr** [comment]
Removed snap

**Comment by Stanzilla** [comment]
Why did you remove Snap? Was it broken?

**Comment by danacr** [comment]
Snap was broken on arm64 and I couldn't figure out the error: https://travis-ci.com/github/danacr/hyper/jobs/379655574#L385

Regarding GitHub actions, there are a couple of options:
- [Running a self-hosted arm64 runnter](https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/), let me know if you want to host one;
- [Travis ci GitHub action](https://github.com/travis-ci/actions) is a nice way to combine the two;
- [Docker buildx](https://github.com/marketplace/actions/docker-buildx) can run builds for a different platform, and it works (this is how I tested the PR), but that would require adding a Dockerfile to the repository and running a secondary GitHub release from inside that container.

Let me know how you would like to proceed.

**Comment by Stanzilla** [comment]
Oh so GH Actions does not have an arm runner yet, okay then. Then I guess the best solution would be to just move everything but the arm build to GH icons and only have travis do arm

**Comment by danacr** [comment]
Are you planning to add the GitHub Actions build artifacts as releases? Travis does not support artifact downloading by default, an s3 bucket should be setup alternatively, or we could use the GitHub releases.

**Comment by Stanzilla** [comment]
I'm not planning with releases at all tbh since the Vercel team is ignoring us when it comes to fixing the flow for that.

**Comment by LabhanshAgrawal** [comment]
> Snap was broken on arm64 and I couldn't figure out the error: [travis-ci.com/github/danacr/hyper/jobs/379655574#L385](https://travis-ci.com/github/danacr/hyper/jobs/379655574#L385)

Isn't it because of https://github.com/vercel/hyper/pull/4852/files#diff-354f30a63fb0907d4ad57269548329e3L27 ?

**Pull request closed without merging**
