### PR TITLE
Remove python dependency in cli on macOS

### LINKED ISSUE #6386: Can't start Hyper from terminal (/opt/homebrew/bin/hyper: line 4: /usr/bin/python: No such file or directory)
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS Monterey 12.3
- **Hyper.app version**: 3.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/GBrachetta/0bb163e8429f9e72f73ea0faf68a4152)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

## Issue

Attempting to invoke Hyper from the terminal (terminal.app or iTerm2) fails:

```bash
$ hyper

$ /opt/homebrew/bin/hyper: line 4: /usr/bin/python: No such file or directory
$ /opt/homebrew/bin/hyper: line 8: ./MacOS/Hyper: No such file or directory
```

Please note my Python installation was done via Homebrew and as I am on an M1 machine all Homebrew installs go under `/opt/homebrew/bin`.

Also, there's no such `./MacOS/Hyper` anywhere. Was it supposed to get created by Hyper? It's not there.

Hyper was also installed with Homebrew.

Maybe Related: 

I cannot run either `Tools/Install Hyper CLI command in PATH`, I get the following error:

Screenshot 2022-03-15 at 14 24 35

### PR DESCRIPTION
**Pull request by zcutlip**
- All system-default python has be removed on macOS 12.3
- Application script should be shell-only, not depending on deprecated runtimes

### CODE REVIEW

**Comment by zcutlip** [comment]
I think this is more suitable than #6387 since python 3 isn't actually installed in macOS by default (despite a python3 shim being present in /usr/bin). Feel free to apply these changes to that PR instead if desired, so @vtj-ttanaka can have credit.

See discussion starting at https://github.com/vercel/hyper/issues/6386#issuecomment-1071037419 for more info.

**Comment by LabhanshAgrawal** [comment]
Looks to be working from the basic checks I did.
Can you check out https://github.com/Microsoft/vscode/blob/main/resources/darwin/bin/code.sh as well? Maybe we can use that directly.

**Comment by LabhanshAgrawal** [comment]
That'd be great, I'm guessing it'd help with the doubts/issue with readlink from the discussion.

**Comment by zcutlip** [comment]
> That'd be great, I'm guessing it'd help with the doubts/issue with readlink from the discussion.

Okay, updated to more closely match VSCode's script. 

Note that bash is deprecated on macOS and will be removed eventually. This script should be updated to either /bin/sh (dash) or /bin/zsh compatibility

**Comment by LabhanshAgrawal** [comment]
Great work. Thanks for your contribution. Will try to wrap things up and do a release this week.

**Pull request merged**
